### ISSUE TITLE
`LWin` mapping works, but `RWin` mapping does not

### ISSUE THREAD

**Issue by austincrft** [pmb6tz/windows-desktop-switcher#13]
When I remap the bottom section with `LWin`, the hotkeys work properly:

```ahk
; User config!
; This section binds the key combo to the switch/create/delete actions
LWin & 1::switchDesktopByNumber(1)
LWin & 2::switchDesktopByNumber(2)
LWin & 3::switchDesktopByNumber(3)
LWin & 4::switchDesktopByNumber(4)
LWin & 5::switchDesktopByNumber(5)
LWin & 6::switchDesktopByNumber(6)
LWin & 7::switchDesktopByNumber(7)
LWin & 8::switchDesktopByNumber(8)
LWin & 9::switchDesktopByNumber(9)
LWin & c::createVirtualDesktop()
```

When I remap the bottom section with `RWin`, the hotkeys do not work properly:

```ahk
; User config!
; This section binds the key combo to the switch/create/delete actions
LWin & 1::switchDesktopByNumber(1)
LWin & 2::switchDesktopByNumber(2)
LWin & 3::switchDesktopByNumber(3)
LWin & 4::switchDesktopByNumber(4)
LWin & 5::switchDesktopByNumber(5)
LWin & 6::switchDesktopByNumber(6)
LWin & 7::switchDesktopByNumber(7)
LWin & 8::switchDesktopByNumber(8)
LWin & 9::switchDesktopByNumber(9)
LWin & c::createVirtualDesktop()
```

I created a test script to verify that `LWin` and `RWin` are working properly in other scripts and it behaves as expected:

```ahk
LWin & 1::Send, testing lwin & 1
RWin & 1::Send, testing rwin & 1
```

Any ideas or insight?

**Comment by pmb6tz** [comment]
I think this issue is because the script itself hits the windows key (it's probably picking RWin) when it does the actual desktop switch. So, you press RWin + 1 to switch desktops, and then the script tries to press Ctrl+RWin+left, but RWin is already pressed. 

I tested locally that to get around this, you need to explicitly change the switchDesktopByNumber function to use LWin and force the duration of the downpress around the key combination. 

`
Send ^#{Right}
`

becomes

`
Send, {CtrlDOWN}{LWinDOWN}{Right}{LWinUP}{CtrlUP}
`

Be sure to replace both 'send' calls (and change "Right" to "Left"). 

I tested this fix on my machine and it works; the downside is that SetKeyDelay is 75ms right now so having more keypresses in the combination introduces a noticeable delay if you switch desktops quickly. To fix that, you should reduce SetKeyDelay to ~20 or so and see if the delay disappears. 

If you find that this resolves the issue and you can get the key delay low enough without bugs, we should just integrate this change.

**Comment by austincrft** [comment]
I was able to get it working with the delay at 20, but I ended up reverting everything anyway.

My laptop doesn't have an `RWin` key, so I can't use the script effectively unless I have a keyboard plugged in. Thanks for the quick reply!

**Comment by Perlence** [comment]
@pmb6tz Didn't want to bring up this issue, but you mentioned `SetKeyDelay`. Did you try to use `SendMode Input`?
