### ISSUE TITLE
Messes up AltGr with nordic keyboard layout 

### ISSUE THREAD

**Issue by huuki** [pmb6tz/windows-desktop-switcher#15]
This messes my AltGr key. I'm using Nordic (Finnish) keyboard layout. It gives AltGr the same function as to Capslock

**Comment by huuki** [comment]
Of course, removing the alternate keys for switching also removes the issue.

**Comment by Elijas** [comment]
@pmb6tz I propose we should comment out (or hide within an IF block with a USE_ALTERNATE_KEYS flag) for the alternate keys, no one will realistically use Caps and CtrlAlt switching combinations at the same time

Either that, or we could Update README so that people can use them :) -> #29

**Comment by pmb6tz** [comment]
I think in general we need a more robust config option. I think we should refactor the config to its own file, and then think about the config experience (in an ideal world, we'd let the user configure their keys when this script is first "installed" but for now a sane config would be fine if well documented). Maybe instead of a USE_ALTERNATE_KEYS flag we could store the key combo in a variable that they can change (and can include suggested key combinations in a comment above the variable). Thoughts?

**Comment by Elijas** [comment]
IMO, having a text-based config is fine for now, unless someone provides a good PR :) 

There could be some utility in being able to write `Ctrl Alt N` instead of `^!N` in the config, but I think just declaring "`^` means `Ctrl`" might be enough.
