### ISSUE TITLE
Hotkey for placing windows on different desktops

### ISSUE THREAD

**Issue by ObviousLeeGitHub** [pmb6tz/windows-desktop-switcher#2]
Hey!

I'm usually not using this platform so I don't know if this is the right place for feature request. Sorry if it's not!

Could you implement a hotkey for placing a window on another desktop? Like pressing Ctrl+Alt+<number of desktop> and the window will be transferred to the specified desktop.

That would make your already great tool near perfect. Thanks for making this either way!

**Comment by jthanto** [comment]
I second this actually, and would ask if @ObviousLeeGitHub didn't already.

**Comment by pmb6tz** [comment]
Yeah, I'll have to figure out a good way to do that but this is something I intend to add if possible. I'll look into it soon. Thanks!

**Comment by fosils** [comment]
This would be an awesome feature!

**Comment by shiro** [comment]
+1 sounds amazing

**Comment by hawkins** [comment]
Definitely agree that this could help a lot. Coming from i3wm on linux, this is my most missed feature. If @pmb6tz doesn't have time to tackle it before I try to, then I'll look into some way to do this here in the next few days.

**Comment by pmb6tz** [comment]
@hawkins I'd appreciate the help, busy times for me so I haven't taken the time yet. If you do, please add a contributors section to the readme as well :-)

**Comment by hawkins** [comment]
While the windows animations make its usage feel a little harsh (especially apparent for those who use windows in a virtual reality setting like me), I found a similar repository on GitHub which has accomplished this task here: [jpginc's Windows 10 Desktop Manager](https://github.com/jpginc/windows10DesktopManager). The specific file associated with this action can be found [here](https://github.com/jpginc/windows10DesktopManager/blob/master/windowMover.ahk).

Although their code is listed under the [Apache License 2.0](https://github.com/jpginc/windows10DesktopManager/blob/master/LICENSE), and thus modification and distribution is allowed, I'm not sure just implementing their solution is the best route here. I'll try to write some code inspired by their solution this weekend, but I'm a rookie when it comes to AHK though, so no hard feelings if someone beats me to the punch.

**Comment by pmb6tz** [comment]
This is the hardest of the proposed features I'd say. @hawkins, ever have any luck prototyping it? I'd love this functionality myself. I disable window animations myself--I can't imagine how dizzying it must be with a VR headset on.

I've seen a few solutions but generally they involve something really hacky like injecting a dll into the current process (to get around limitations in the windows API).

**Comment by hawkins** [comment]
Unfortunately, the best solution I could get was an even hackier version of the `windowMover.ahk` I mentioned in my previous comment. 

Implementing JPGinc's desktopManager and windowMover was the best course of action I have found. I'll get on this after lunch and set a reminder to comment back tonight with what progress I've made.

**Comment by hawkins** [comment]
No dice. Couldn't make Jpginc's solution work at all, today. Not integrated in your project nor his own clean project.

Anyone have any ideas that don't rely on including DLLs?

**Comment by pmb6tz** [comment]
Tough problem--I'll give it another pass soon :-). Thanks for taking a look.

**Comment by pmb6tz** [comment]
@Elijas FYI - this is an open feature request that I believe your PR will solve. Be sure to reference it :-).

**Comment by Elijas** [comment]
I'm not sure what hotkey could be used for this?
1. Using three combo keys for `Shift + Caps + 1` hotkey is not possible ([source](https://www.autohotkey.com/docs/Hotkeys.htm#combo))
2. Using two combo keys `Caps + 1` then checking if Shift is pressed down `GetKeyState(Shift)` inside the function didn't work because `Caps + 1` didn't get triggered at all when holding a modifier key. Although, according to the [docs](GetKeyState) it should! `For example, 1 & 2:: will activate even if Ctrl or Alt is held down when 1 and 2 are pressed`
3. For now it's `Caps + 1` for switching, and the button below 1 for moving: `Caps + q`
In alternate configuration, it's `Ctrl + Alt + 1` for switching, `Ctrl + Win + 1` for moving
4. What also could be used is the CapsLock/NumLock/ScrollLock state (e.g. if ON, then `Caps + 1` will move the window and then switch to it, else it will just switch to it)

PR that fixes this issue -> https://github.com/pmb6tz/windows-desktop-switcher/pull/28
