### ISSUE TITLE
retain focus on windows

### ISSUE THREAD

**Issue by shiro** [pmb6tz/windows-desktop-switcher#4]
It would be great if there was an option to remember the active window before switching at every desktop, so it would be focused once switched back.
I assume a simple alt+tab won't work, since it produces unexpected behaviour at rapid switching. You would probably need to store some window UUIDs, assuming that's doable.

**Comment by hawkins** [comment]
Another interesting idea! Would love to see this added as well

**Comment by pmb6tz** [comment]
Good idea, it's one of my pet peeves. [This post ](http://autohotkey.com/board/topic/54030-resolved-activate-last-active-window-what-is-wrong/?p=338909) seems pretty similar to what we want here--we'd need to store a guid for the active window on each virtual desktop but that's certainly not impossible. If one of you wants to take a crack at it feel free, otherwise I'll get to it when I do :-).

**Comment by pestaa** [comment]
@pmb6tz According to the thread you linked to, Alt+Esc does the trick most of the time -- it is certainly good enough for me for now!

**Comment by Elijas** [comment]
I've hacked together the window re-focus code (into my copy of this repo, haven't released publicly though) from the more robust solution linked in the README, works wonderfully!

It's easily possible with the dll provided there.

**Comment by pmb6tz** [comment]
@Elijas , this should be fixed now, correct?

**Comment by Elijas** [comment]
> @Elijas , this should be fixed now, correct?

Correct, it's fixed. This is the sole purpose of the DLL.

One note, if there's any issues in the future, [original example code](https://github.com/Ciantic/VirtualDesktopAccessor) has some extra code (`activeWindowByDesktop`) regarding active windows, it may or may not be useful fixing the bugs
