### ISSUE TITLE
Show current desktop number in the tray bar

### ISSUE THREAD

**Issue by cesera** [pmb6tz/windows-desktop-switcher#50]
Thank you so much for this script. This has been the one thing that has been bothering me with the Windows virtual desktops, and now they are finally workable.

I don't know if you do feature requests, but just in case: Would it be possible to show the number of the current virtual desktop on the system tray icon? That way I always know what desktop I'm on.

**Comment by Elijas** [comment]
Hi, We're glad you've found the script useful!

You can check out an alternative to our script which has dynamic tray icons that you're looking for, and other additional features: [sdias/win-10-virtual-desktop-enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer).

Also, I've worked on a [pull request #34 ](https://github.com/pmb6tz/windows-desktop-switcher/pull/34) before, on this exact feature that you're asking for. If I remember, the implementation didn't work in as stable and fast manner as without having the tray icons, so I decided to scrap it at the time.

If someone would want to implement this, there are plenty of code examples and the icons themselves in [sdias/win-10-virtual-desktop-enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer) and [pull request #34 ](https://github.com/pmb6tz/windows-desktop-switcher/pull/34) .

**Comment by cesera** [comment]
Thank you so much for your reply. I used to use alternative script until about a year ago, when it stopped working. So I’ll just keep going as I am doing at the moment. Unfortunately I don’t have the time, or the skills (or the time to learn the skills) to implement this myself.

Thank you so much for sharing your script with us though. It makes live so much easier.

Blessings,
Kees

**Comment by Elijas** [comment]
Most likely it stopped working due to the DLL failing compatibility with the newer version of Windows. You might be able to continue using the other script if you replace 
- This file in the other repository https://github.com/sdias/win-10-virtual-desktop-enhancer/tree/master/libraries `virtual-desktop-accessor.dll`
- With the DLL that is found in our repository (be sure to rename it to `virtual-desktop-accessor.dll`)

**Comment by cesera** [comment]
Thank you so much, that works. That will save me a lot of clicking around. You have no idea how much I appreciate that.

Blessings,
Kees

**Comment by Elijas** [comment]
No problem! Feel free to [support](https://ko-fi.com/elijas) the project if you've found it useful.

**Comment by adamency** [comment]
What is the current status of adding this feature to the project ? Especially considering the recommended alternative project is unmaintained since 2018.

**Comment by Elijas** [comment]
It has been a while, but AFAIR It's not that hard to add this feature if users always changed their desktops using the app alone. You'd just need to add "Change tray icon" command after the "Change Desktop" command in the code (I did this before: https://github.com/pmb6tz/windows-desktop-switcher/pull/34).

It's more difficult when detection is needed for users switching desktops through Windows UI, etc. I started working on it, but bug corner cases kept popping up, so I didn't release the feature, because it was somewhat buggy, but did not have the resources to work on it further either. I believe there was some slight but noticeable impact on performance, but I can't remember exactly.

Status? If someone made a robustly working status icon changing functionality without noticeable impact on performance, would be happy to review and include it to the project. I, myself, unfortunately don't work on new features for this project anymore.

**Comment by adamency** [comment]
Alright, thanks for the answer.

Just wanted to let other users of this project aware of this little repo written in C# that implements this feature in an atomic way, and perfectly works independently and concurrently to this project: https://github.com/zgdump/windows-virtualdesktopindicator

Works with Windows UI and through this application.

**Comment by Elijas** [comment]
@adamency This is awesome, I'll add it to the README.md

**Comment by whitenoisedev** [comment]
This util works with Win11 22H2. <https://github.com/dankrusi/WindowsVirtualDesktopHelper>
